<?php

/**
 * Copyright [2014] [Dexxtz]
 *
 * @package   Dexxtz_Customaddress
 * @author    Dexxtz
 * @license   http://www.apache.org/licenses/LICENSE-2.0
 */
 
?>
<?php 
	$helper = Mage::helper('customaddress'); 
	$helper->checkStates();
	$storeCode = Mage::app()->getStore()->getLocaleCode();
?>

<script type="text/javascript">
	var jQuery = jQuery.noConflict();
	jQuery(document).ready(function() {
		jQuery('#shipping-new-address-form .state_autocomplete').addClass('validate-select');
		jQuery('#shipping-new-address-form .state_autocomplete').addClass('required-entry');
	});
	
	function getStates() { 
		return 	JSON.parse('<?php echo json_encode($_SESSION['states']) ?>');
	}
</script>

<form action="" id="co-shipping-form">
    <ul class="form-list">
    <?php if ($this->customerHasAddresses()): ?>
       <li class="wide">
           <label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
           <div class="input-box">
               <?php echo $this->getAddressesHtmlSelect('shipping') ?>
           </div>
       </li>
    <?php endif ?>    	
        <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
            <fieldset>
                <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                <ul>
                    <li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->setFieldParams('onchange="shipping.setSameAsBilling(false)"')->toHtml() ?></li>
                    <?php if ($helper->getCompany() == 1) { ?>
                    <li class="fields">
                        <div class="fields">
                            <label for="shipping:company"><?php echo $helper->__('Company') ?></label>
                            <div class="input-box">
                                <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $helper->__('Company') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </div>
                    </li>
                    <?php } ?>
                    <li class="fields">
			            <div class="field">
			                <label for="shipping:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
			                <div class="input-box">
			                    <input type="text" name="shipping[telephone]"<?php echo $helper->addMask(16, $storeCode);?> value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" onchange="shipping.setSameAsBilling(false);" />
			                </div>
			            </div>
			            <div class="field">
			                <label for="shipping:fax"><?php echo $helper->__('Fax') ?></label>
			                <div class="input-box">
			                    <input type="text" name="shipping[fax]"<?php echo $helper->addMask(17, $storeCode);?> value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $helper->__('Fax') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" id="shipping:fax" onchange="shipping.setSameAsBilling(false);" />
			                </div>
			            </div>
			        </li>
			        <li class="fields">
			        	<div class="field">
			                <label for="shipping:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
			                <div class="input-box">
			                    <input type="text"<?php echo $helper->getAutoComplete('zip_autocomplete', true, true) . $helper->addZipMask($storeCode);?> title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international<?php echo $helper->getAutoComplete(' zip_autocomplete ') . $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" onchange="shipping.setSameAsBilling(false);" />
			                </div>
			            </div>
			            <?php if ($storeCode == 'pt_BR' && $helper->getZipLink() == 1) { ?>
			            <br />
			            <div class="field">
			            	<div class="input-box">
			                	<a class="not_know_zip" target="_blank" href="http://www.buscacep.correios.com.br/">
			                		<?php echo $helper->getZipText(); ?>
			                	</a>
			            	</div>               	
			            </div> 
			            <?php } ?>
			        </li>
	                <li class="fields">
	                	<div class="field">
		                    <label for="shipping:street_1" class="required"><em>*</em><?php echo $helper->__('Address') ?></label>
		                    <div class="input-box">
		                        <input type="text" title="<?php echo $helper->__('Address') ?>" name="shipping[street][]" id="shipping:street_1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text required-entry<?php echo $helper->getAutoComplete(' street1_autocomplete');?>" />
		                    </div>
		            	</div>
		            	<div class="field">
		                    <label for="shipping:street_2" class="required"><em>*</em><?php echo $helper->__('Number') ?></label>
		                    <div class="input-box">
		                        <input type="text" title="<?php echo $helper->__('Number') ?>" name="shipping[street][]" id="shipping:street_2" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(2)) ?>" class="input-text required-entry" />
		                    </div>
		            	</div>
	                </li>
	                <li class="fields">
	                	<div class="field">
		                    <label for="shipping:street_3" class="required"><em>*</em><?php echo $helper->__('Region') ?></label>
		                    <div class="input-box">
		                        <input type="text" title="<?php echo $helper->__('Region') ?>" name="shipping[street][]" id="shipping:street_3" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(3)) ?>" class="input-text required-entry<?php echo $helper->getAutoComplete(' street3_autocomplete');?>" />
		                    </div>
		            	</div>
		            	<div class="field">
		                    <label for="shipping:street_4"><?php echo $helper->__('Complement') ?></label>
		                    <div class="input-box">
		                        <input type="text" title="<?php echo $helper->__('Complement') ?>" name="shipping[street][]" id="shipping:street_4" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(4)) ?>" class="input-text" />
		                    </div>
		            	</div>
	                </li>
                    <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                    <li class="wide">
                        <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
                        <div class="input-box">
                            <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                        </div>
                    </li>
                    <?php endif; ?>
                    <li class="fields">
                        <div class="field">
                            <label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" class="input-text<?php echo $helper->getAutoComplete(' city_autocomplete ') . $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="shipping:city" onchange="shipping.setSameAsBilling(false);" />
                            </div>
                        </div>
                        <div class="field">
                            <label class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                            <div class="input-box">
                                <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select<?php echo $helper->getAutoComplete(' state_autocomplete');?>" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                //<![CDATA[
                                    $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                                //]]>
                                </script>
                                <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>" class="input-text<?php echo $helper->getAutoComplete(' state_autocomplete ') . $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                            </div>
                        </div>
                    </li>
                    <li class="fields"<?php if ($helper->getCountry() == 0) { echo ' style="display:none;"'; } ?>>
                        <div class="field">
                            <label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                            <div class="input-box">
                                <?php echo $this->getCountryHtmlSelect('shipping') ?>
                            </div>
                        </div>
                    </li>                    
                <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                    <li class="control">
                        <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" onchange="shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><label for="shipping:save_in_address_book"><?php echo $this->__('Save in address book') ?></label></li>
                <?php else:?>
                    <li class="no-display"><input type="hidden" name="shipping[save_in_address_book]" value="1" /></li>
                <?php endif;?>
                </ul>
            </fieldset>
        </li>
        <li class="control">
            <input type="checkbox" name="shipping[same_as_billing]" id="shipping:same_as_billing" value="1"<?php if($this->getAddress()->getSameAsBilling()): ?> checked="checked"<?php endif; ?> title="<?php echo $this->__('Use Billing Address') ?>" onclick="shipping.setSameAsBilling(this.checked)" class="checkbox" /><label for="shipping:same_as_billing"><?php echo $this->__('Use Billing Address') ?></label>
        </li>
    </ul>
    <div class="buttons-set" id="shipping-buttons-container">
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
        <p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="button" class="button" title="<?php echo $this->__('Continue') ?>" onclick="shipping.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
        <span id="shipping-please-wait" class="please-wait" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
        </span>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var shipping = new Shipping('co-shipping-form', '<?php echo $this->getUrl('checkout/onepage/getAddress') ?>address/', '<?php echo $this->getUrl('checkout/onepage/saveShipping') ?>',
        '<?php echo $this->getUrl('checkout/onepage/shippingMethod') ?>');
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    $('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);

    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
//]]>
</script>
