<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$helper = $this->helper('flexibletheme');
$verticalMenu = $helper->getConfig('flexibletheme/header/vertical_menu');
?>

<?php if ($verticalMenu) : ?>
<?php echo $this->getLayout()->createBlock('megamenupro/widget_megamenu')->setMenu($verticalMenu)->setType(1)->toHtml(); ?>
<?php endif ?>