<?php
/**
 * Copyright © 2017 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$_productCollection = $this->getProductCollection();
$_helper = $this->helper('catalog/output');
$labelHelper = $this->getLabelHelper();
$quickShopHelper = $this->helper('quickviewpro');
$imageHelper = $this->helper('catalog/image');
$wishlistHelper = $this->helper('wishlist');
$showSlider = $this->getData('show_slider');

$width = $this->getData('thumb_width');
$height = $this->getData('thumb_height');
$paddingBottom = $height*100/$width;

$showDescription = $this->isShow('description');
$showSku = $this->isShow('sku');
$showWishlist = $this->isShow('wishlist') && $wishlistHelper->isAllow();
$showCompare = $this->isShow('compare');
$showCart = $this->isShow('addtocart');
$showQuickShop = $this->isShow('quickshop');
$showLabel = $this->isShow('label');
$showThumb = $this->isShow('thumb');
$showName = $this->isShow('name');
$showReview = $this->isShow('review');
$showPrice = $this->isShow('price');
$largeWidth = 700;
$largeHeight = $height*$largeWidth/$width;

$totalRows = (int)$this->getData('total_rows');
$totalCols = (int)$this->getData('total_cols');
$uniqid = uniqid();
$widget = array('codazon.isogrid' => array('sliderConfig' => $this->getSliderData()));

$gallery = $this->getLayout()->createBlock('catalog/product_view_media')
    ->setTemplate('codazon_productfilterpro/elements/gallery.phtml')
    ->addData(array(
        'image_width'       => $largeWidth,
        'image_height'      => $largeHeight,
        'small_width'       => 200,
        'moreview_settings' => array(
            'items'     => 4,
            'nav'       => 1,
            'dots'      => 0,
            'margin'    => 20
        )
    ));
    
?>

<?php if($_count = $_productCollection->count()): ?>
<div class="grid-style-06 products">
<div class="products list items product-items" data-cdzwidget='<?= json_encode($widget) ?>'>
<?php foreach ($_productCollection as $_product): ?>
<?php
$name = $this->stripTags($_product->getName(), null, true);
$url = $_product->getProductUrl();
?>
        <div class="item product product-item">
            <div class="product-item-info">
                <div class="product-item-top">
                    <a href="<?= $url ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image abs-img" style="padding-bottom: <?php echo $paddingBottom ?>%">
                        <img class="product-image-photo main-img"
                            data-largeimg="<?= $imageHelper->init($_product, 'small_image')->resize($largeWidth, $largeHeight); ?>"
                            data-smallimage="<?= $imageHelper->init($_product, 'small_image')->resize($width, $height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        <img class="product-image-photo hovered-img"
                            data-largeimg="<?= $imageHelper->init($_product, 'thumbnail')->resize($largeWidth, $largeHeight); ?>"
                            data-smallimage="<?= $imageHelper->init($_product, 'thumbnail')->resize($width, $height); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" />
                    </a>
                    <?= $showLabel?$labelHelper->showLabel($_product):''; ?>
                    <?php if ($showWishlist || $showCompare): ?>
                    <div class="button-top-wrap" data-role="add-to-links">
                        <?php if ($showWishlist) : ?>
                        <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="towishlist link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                        <?php endif; ?>
                        <?php if(($_compareUrl=$this->getAddToCompareUrl($_product)) && $showCompare): ?>
                        <a href="<?php echo $_compareUrl ?>" class="tocompare link-compare"><?php echo $this->__('Add to Compare') ?></a>
                        <?php endif; ?>
                    </div>
                    <?php endif ?>
                    <div class="product-hovered-section">
                        <div class="product-details eq-h">
                            <?php if ($showName): ?>
                            <strong class="product-name"><a class="product-item-link" href="<?= $_product->getProductUrl(); ?>"><?= $name; ?></a></strong>
                            <?php endif ?>
                            <?= $showPrice ? $this->getPriceHtml($_product, true, $uniqid) : '' ?>
                            <?php if ($showSku) : ?>
                                <div class="product-item-sku"><span class="label"><?= __('SKU: ') ?></span><span class="value"><?= $_product->getData('sku') ?></span></div>
                            <?php endif ?>
                            <?= $showReview ? $this->getReviewsSummaryHtml($_product, 'short') : ''; ?>
                        </div>
                        <div class="button-hover-wrap">
                            <?= $showQuickShop?$quickShopHelper->getQuickShopButton($_product):''; ?>
                            <?php if ($_product->isSaleable()) : ?>
                                <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php else : ?>
                                <button type="button" title="<?php echo $this->quoteEscape($this->__('Out of stock')) ?>" class="button btn-cart out-of-stock disabled unavailable"disabled><span><span><?php echo $this->__('Out of stock') ?></span></span></button>
                            <?php endif ?>
                        </div>
                    </div>
                </div>
                <div class="product details product-item-details product-info">
                    <?= $gallery->setProduct($_product)->toHtml(); ?>
                    <div class="detail-items-wrap">
                        <div class="product-box">
                            <div class="left-box">
                                <?php if ($showName): ?>
                                <strong class="product-name"><a class="product-item-link" href="<?= $_product->getProductUrl(); ?>"><?= $name; ?></a></strong>
                                <?php endif ?>
                                <?php if ($showSku) : ?>
                                    <div class="product-item-sku"><span class="label"><?= __('SKU: ') ?></span><span class="value"><?= $_product->getData('sku') ?></span></div>
                                <?php endif ?>
                                <?php if ($showDescription):?>
                                    <div class="product description product-item-description">
                                        <?= $this->subString($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), 70) ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                            <div class="right-box">
                                <?= $showPrice ? $this->getPriceHtml($_product, true, $uniqid . '_2') : '' ?>
                                <?= $showReview ? $this->getReviewsSummaryHtml($_product, 'short') : ''; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<?php endforeach ?>
</div>
</div>
<?php else : ?>
<div class="note-msg"><div><?php echo $this->__('There are no products matching the selection.') ?></div></div>
<?php endif ?>