<?php
/**
 * Copyright © 2017 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$_productCollection = $this->getProductCollection();
$_helper            = $this->helper('catalog/output');
$labelHelper        = $this->getLabelHelper();
$quickShopHelper    = $this->helper('quickviewpro');
$imageHelper        = $this->helper('catalog/image');
$wishlistHelper     = $this->helper('wishlist');
$showSlider         = $this->getData('show_slider');

$width         = $this->getData('thumb_width');
$height        = $this->getData('thumb_height');
$paddingBottom = $height * 100 / $width;

$showDescription = $this->isShow('description');
$showSku         = $this->isShow('sku');
$showWishlist    = $wishlistHelper->isAllow() && $this->isShow('wishlist');
$showCompare     = $this->isShow('compare');
$showCart        = $this->isShow('addtocart');
$showQuickShop   = $this->isShow('quickshop');
$showLabel       = $this->isShow('label');
$showThumb       = $this->isShow('thumb');
$showName        = $this->isShow('name');
$showReview      = $this->isShow('review');
$showPrice       = $this->isShow('price');

$totalRows = (int) $this->getData('total_rows');
$totalCols = (int) $this->getData('total_cols');
$uniqid    = uniqid();
$widget    = array('codazon.slider' => array('sliderConfig' => $this->getSliderData()));

?>

<?php if ($_count = $_productCollection->count()): ?>
<div class="grid-style-19 products">
<div class="products list items product-items<?=$showSlider ? ' owl-carousel' : ''?>" <?php if ($showSlider): ?>data-cdzwidget='<?=json_encode($widget)?>'<?php endif?>>
<?php $i = 0;foreach ($_productCollection as $_product): ?>
<?php
$name = $this->stripTags($_product->getName(), null, true);
$url  = $_product->getProductUrl();
?>
    <?php if ($i % $totalRows == 0): ?>
    <div class="item-group">
    <?php endif?>
        <div class="item product product-item">
            <div class="product-item-info">
                <div class="product-item-top">
                    <a href="<?=$url?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image abs-img" style="padding-bottom: <?php echo $paddingBottom ?>%">
                        <img class="product-image-photo main-img" src="<?=$imageHelper->init($_product, 'small_image')->resize($width, $height);?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        <img class="product-image-photo hovered-img" src="<?=$imageHelper->init($_product, 'thumbnail')->resize($width, $height);?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" />
                    </a>
                    <?=$showLabel ? $labelHelper->showLabel($_product) : '';?>
                    <?=$showQuickShop ? $quickShopHelper->getQuickShopButton($_product) : '';?>
                    <?php if ($showCompare || $showWishlist) : ?>
                    <div class="button-top-wrap">
                        <?php if (($_compareUrl = $this->getAddToCompareUrl($_product)) && $showCompare): ?>
                            <a href="<?php echo $_compareUrl ?>" class="tocompare link-compare"><?php echo $this->__('Add to Compare') ?></a>
                        <?php endif;?>
                        <?php if ($showWishlist): ?>
                            <a href="<?php echo $wishlistHelper->getAddUrl($_product) ?>" class="towishlist link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                        <?php endif;?>
                    </div>
                    <?php endif ?>
                </div>
                <div class="product details product-item-details product-info">
                    <div class="detail-items-wrap">
                        <?php if ($showName): ?>
                        <strong class="product-name">
                            <a class="product-item-link" href="<?=$_product->getProductUrl();?>">
                                <?=$name;?>
                            </a>
                        </strong>
                        <?php endif?>
                        <?php if ($showSku): ?>
                        <div class="product-item-sku"><span class="label"><?=__('SKU: ')?></span><span class="value"><?=$_product->getData('sku')?></span></div>
                        <?php endif?>

                        <?=$showReview ? $this->getReviewsSummaryHtml($_product, 'short') : '';?>
                        <?=$showPrice ? $this->getPriceHtml($_product, true, $uniqid) : ''?>
                        <?php if ($showDescription): ?>
                        <div class="product description product-item-description">
                            <?=$this->subString($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), 70)?>
                        </div>
                        <?php endif;?>
                    </div>
                    <div class="product-item-inner">
                        <div class="product actions product-item-actions">
                            <?php if ($showCart): ?>
                            <div class="button-wrap">
                                <?php if ($showCart): ?>
                                <div class="cart-qty">
                                 <?php if ($_product->isSaleable()): ?>
                                        <form action="<?= $this->getAddToCartUrl($_product) ?>" class="add-to-cart-form js-mini-form">
                                            
                                            <div class="field qty">
                                                <label class="label" for="qty"><span><?= $this->__('Qty') ?></span></label>
                                                <div class="control">
                                                    <div class="qty-ctl">
                                                        <button aria-label="<?= $this->__('Decrease') ?>" type="button" data-role="change_cart_qty" class="decrease" data-qty="-1" class="decrease"></button>
                                                    </div>
                                                    <input type="text" class="qty" name="qty" maxlength="12" value="<?= $this->getProductDefaultQty($_product) * 1 ?>" title="<?= $this->__('Qty') ?>" class="input-text qty" />
                                                    <div class="qty-ctl">
                                                        <button aria-label="<?= $this->__('Increase') ?>" type="button" data-role="change_cart_qty" data-qty="1" class="increase"></button>
                                                    </div>
                                                </div>
                                            </div>
                                            <button type="submit" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                        </form>
                                    <?php else: ?>
                                        <button type="button" title="<?php echo $this->quoteEscape($this->__('Out of stock')) ?>" class="button btn-cart out-of-stock disabled unavailable"disabled><span><span><?php echo $this->__('Out of stock') ?></span></span></button>
                                    <?php endif?>
                                <?php endif ?>
                                </div>
                            </div>
                            <?php endif;?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <?php if (($i % $totalRows == ($totalRows - 1)) || ($i == ($_count - 1))): ?>
    </div>
    <?php endif?>
<?php $i++;endforeach?>
</div>
</div>
<?php else: ?>
<div class="note-msg"><div><?php echo $this->__('There are no products matching the selection.') ?></div></div>
<?php endif?>