<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
$_themeHelper = $this->helper('flexibletheme');
?>
<script>
if (typeof ProductMediaManager.oldSwapImage === 'undefined') {
    ProductMediaManager.oldSwapImage = ProductMediaManager.swapImage;
    ProductMediaManager.swapImage = function(targetImage) {
        ProductMediaManager.oldSwapImage(targetImage);
        var imageGallery = $j('.product-image-gallery');
        var src = targetImage.attr('src');
        targetImage.attr('data-src', src);
        imageGallery.trigger('swapImageCompleted');
    };
    ProductMediaManager.createZoom = function(image) {
        if (typeof $j.fn.elevateZoom == 'undefined') {
            return;
        }
        ProductMediaManager.destroyZoom();
        if(
            PointerManager.getPointer() == PointerManager.TOUCH_POINTER_TYPE
            || Modernizr.mq("screen and (max-width:" + bp.medium + "px)")
        ) {
            return;
        }

        if(image.length <= 0) {
            return;
        }

        if(image[0].naturalWidth && image[0].naturalHeight) {
            var widthDiff = image[0].naturalWidth - image.width() - ProductMediaManager.IMAGE_ZOOM_THRESHOLD;
            var heightDiff = image[0].naturalHeight - image.height() - ProductMediaManager.IMAGE_ZOOM_THRESHOLD;

            if(widthDiff < 0 && heightDiff < 0) {
                image.parents('.product-image').removeClass('zoom-available');
                return;
            } else {
                image.parents('.product-image').addClass('zoom-available');
            }
        }
        <?php if ($_themeHelper->getConfig('product_view/design/enable_zoom_lens')) : ?>
        image.elevateZoom({
            zoomType: "lens",
            lensShape : "round",
            containLensZoom: true,
            lensSize    : <?php echo ((float)$_themeHelper->getConfig('product_view/design/lens_width')) ? : 300; ?>,
            borderSize: 0,
            tintOpacity: 0.4
        });
        <?php endif ?>
    }
}
</script>