<?php

/**
 * SizeChart setup
 *
 * @category    Ave
 * @package     Ave_SizeChart
 * @author      averun <dev@averun.com>
 */
class Ave_SizeChart_Model_Resource_Setup extends Mage_Catalog_Model_Resource_Setup
{

    /**
     * get the default entities for sizechart module - used at installation
     *
     * @access public
     * @return array()
     * @author averun <dev@averun.com>
     */
    public function getDefaultEntities()
    {
        $entities = array();
        $entities['ave_sizechart_chart'] = array(
            'entity_model'                  => 'ave_sizechart/chart',
            'attribute_model'               => 'ave_sizechart/resource_eav_attribute',
            'table'                         => 'ave_sizechart/chart',
            'additional_attribute_table'    => 'ave_sizechart/eav_attribute',
            'entity_attribute_collection'   => 'ave_sizechart/chart_attribute_collection',
            'attributes'                    => array(
                'name' => array(
                    'group'          => 'General',
                    'type'           => 'varchar',
                    'backend'        => '',
                    'frontend'       => '',
                    'label'          => 'Name',
                    'input'          => 'text',
                    'source'         => '',
                    'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                    'required'       => '1',
                    'user_defined'   => false,
                    'default'        => '',
                    'unique'         => false,
                    'position'       => '1',
                    'note'           => '',
                    'visible'        => '1',
                    'wysiwyg_enabled'=> '0',
                ),
                'category_id' => array(
                    'group'          => 'General',
                    'type'           => 'int',
                    'backend'        => '',
                    'frontend'       => '',
                    'label'          => 'Category of sizes',
                    'input'          => 'select',
                    'source'         => 'ave_sizechart/category_source',
                    'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
                    'required'       => '',
                    'user_defined'   => true,
                    'default'        => '',
                    'unique'         => false,
                    'position'       => '3',
                    'note'           => '',
                    'visible'        => '1',
                    'wysiwyg_enabled'=> '0',
                ),
                'type_id' => array(
                    'group'          => 'General',
                    'type'           => 'int',
                    'backend'        => '',
                    'frontend'       => '',
                    'label'          => 'Type',
                    'input'          => 'select',
                    'source'         => 'ave_sizechart/type_source',
                    'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
                    'required'       => '',
                    'user_defined'   => true,
                    'default'        => '',
                    'unique'         => false,
                    'position'       => '5',
                    'note'           => '',
                    'visible'        => '1',
                    'wysiwyg_enabled'=> '0',
                ),
                'dimension_id' => array(
                    'group'          => 'General',
                    'type'           => 'text',
                    'backend'        => 'eav/entity_attribute_backend_array',
                    'frontend'       => '',
                    'label'          => 'Dimension',
                    'input'          => 'multiselect',
                    'source'         => 'ave_sizechart/dimension_source',
                    'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
                    'required'       => '',
                    'user_defined'   => true,
                    'default'        => '',
                    'unique'         => false,
                    'position'       => '7',
                    'note'           => 'There are columns for size table. Includes dimensions and regions. Two in one.'
                                      . ' Click Save to apply the changes about the columns',
                    'visible'        => '1',
                    'wysiwyg_enabled'=> '0',
                ),
                'product_category' => array(
                    'group'           => 'General',
                    'type'            => 'text',
                    'backend'         => 'eav/entity_attribute_backend_array',
                    'frontend'        => '',
                    'label'           => 'Product Category',
                    'input'           => 'multiselect',
                    'source'          => 'ave_sizechart/chart_attribute_source_productcategory',
                    'global'          => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
                    'required'        => '0',
                    'user_defined'    => true,
                    'default'         => '',
                    'unique'          => false,
                    'position'        => '9',
                    'note'            => 'For products in selected categories will be available this table sizes. '
                                       . 'For one category will always be only one table available sizes',
                    'visible'         => '1',
                    'wysiwyg_enabled' => '0',
                ),
                'description' => array(
                    'group'          => 'General',
                    'type'           => 'text',
                    'backend'        => '',
                    'frontend'       => '',
                    'label'          => 'Description',
                    'input'          => 'textarea',
                    'source'         => '',
                    'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                    'required'       => '1',
                    'user_defined'   => true,
                    'default'        => '',
                    'unique'         => false,
                    'position'       => '11',
                    'note'           => 'The text will be displayed under table with sizes in right sidebar',
                    'visible'        => '1',
                    'wysiwyg_enabled'=> '1',
                ),
                'note' => array(
                    'group'          => 'General',
                    'type'           => 'varchar',
                    'backend'        => '',
                    'frontend'       => '',
                    'label'          => 'Note',
                    'input'          => 'text',
                    'source'         => '',
                    'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                    'required'       => '',
                    'user_defined'   => true,
                    'default'        => '',
                    'unique'         => false,
                    'position'       => '13',
                    'note'           => 'The text will be displayed under user dimension fields in left sidebar',
                    'visible'        => '1',
                    'wysiwyg_enabled'=> '0',
                ),
                'image' => array(
                    'group'          => 'General',
                    'type'           => 'varchar',
                    'backend'        => 'ave_sizechart/chart_attribute_backend_image',
                    'frontend'       => '',
                    'label'          => 'Image',
                    'input'          => 'image',
                    'source'         => '',
                    'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                    'required'       => '1',
                    'user_defined'   => true,
                    'default'        => '',
                    'unique'         => false,
                    'position'       => '15',
                    'note'           => '',
                    'visible'        => '1',
                    'wysiwyg_enabled'=> '0',
                ),
                'status' => array(
                    'group'          => 'General',
                    'type'           => 'int',
                    'backend'        => '',
                    'frontend'       => '',
                    'label'          => 'Enabled',
                    'input'          => 'select',
                    'source'         => 'eav/entity_attribute_source_boolean',
                    'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                    'required'       => '1',
                    'user_defined'   => false,
                    'default'        => '1',
                    'unique'         => false,
                    'position'       => '17',
                    'note'           => '',
                    'visible'        => '1',
                    'wysiwyg_enabled'=> '0',
                ),
            )
         );
        $entities['ave_sizechart_category'] = array(
            'entity_model'                  => 'ave_sizechart/category',
            'attribute_model'               => 'ave_sizechart/resource_eav_attribute',
            'table'                         => 'ave_sizechart/category',
            'additional_attribute_table'    => 'ave_sizechart/eav_attribute',
            'entity_attribute_collection'   => 'ave_sizechart/category_attribute_collection',
            'attributes'                    => array(
                    'name' => array(
                        'group'          => 'General',
                        'type'           => 'varchar',
                        'backend'        => '',
                        'frontend'       => '',
                        'label'          => 'Name',
                        'input'          => 'text',
                        'source'         => '',
                        'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required'       => '1',
                        'user_defined'   => false,
                        'default'        => '',
                        'unique'         => false,
                        'position'       => '10',
                        'note'           => 'Men, Women, Boy, Girl, etc.',
                        'visible'        => '1',
                        'wysiwyg_enabled'=> '0',
                    ),
                    'position' => array(
                        'group'          => 'General',
                        'type'           => 'int',
                        'backend'        => '',
                        'frontend'       => '',
                        'label'          => 'Position',
                        'input'          => 'text',
                        'source'         => '',
                        'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
                        'required'       => '0',
                        'user_defined'   => true,
                        'default'        => '',
                        'unique'         => false,
                        'position'       => '20',
                        'note'           => '',
                        'visible'        => '1',
                        'wysiwyg_enabled'=> '0',
                    ),
                    'status' => array(
                        'group'          => 'General',
                        'type'           => 'int',
                        'backend'        => '',
                        'frontend'       => '',
                        'label'          => 'Enabled',
                        'input'          => 'select',
                        'source'         => 'eav/entity_attribute_source_boolean',
                        'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required'       => '1',
                        'user_defined'   => false,
                        'default'        => '1',
                        'unique'         => false,
                        'position'       => '30',
                        'note'           => '',
                        'visible'        => '1',
                        'wysiwyg_enabled'=> '0',
                    ),

                )
         );
        $entities['ave_sizechart_dimension'] = array(
            'entity_model'                  => 'ave_sizechart/dimension',
            'attribute_model'               => 'ave_sizechart/resource_eav_attribute',
            'table'                         => 'ave_sizechart/dimension',
            'additional_attribute_table'    => 'ave_sizechart/eav_attribute',
            'entity_attribute_collection'   => 'ave_sizechart/dimension_attribute_collection',
            'attributes'                    => array(
                    'name' => array(
                        'group'          => 'General',
                        'type'           => 'varchar',
                        'backend'        => '',
                        'frontend'       => '',
                        'label'          => 'Name',
                        'input'          => 'text',
                        'source'         => '',
                        'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required'       => '1',
                        'user_defined'   => false,
                        'default'        => '',
                        'unique'         => false,
                        'position'       => '10',
                        'note'           => 'neck, torso, arm length, chest, bust, natural waist, waist, seat, hips,'
                                            . ' inseam',
                        'visible'        => '1',
                        'wysiwyg_enabled'=> '0',
                    ),
                    'description' => array(
                        'group'          => 'General',
                        'type'           => 'varchar',
                        'backend'        => '',
                        'frontend'       => '',
                        'label'          => 'Description',
                        'input'          => 'text',
                        'source'         => '',
                        'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required'       => '1',
                        'user_defined'   => true,
                        'default'        => '',
                        'unique'         => false,
                        'position'       => '20',
                        'note'           => '',
                        'visible'        => '1',
                        'wysiwyg_enabled'=> '0',
                    ),
                    'type' => array(
                        'group'          => 'General',
                        'type'           => 'varchar',
                        'backend'        => '',
                        'frontend'       => '',
                        'label'          => 'Type',
                        'input'          => 'select',
                        'source'         => 'ave_sizechart/dimension_attribute_source_type',
                        'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
                        'required'       => '1',
                        'user_defined'   => true,
                        'default'        => '',
                        'unique'         => false,
                        'position'       => '30',
                        'note'           => '',
                        'visible'        => '1',
                        'wysiwyg_enabled'=> '0',
                        'option' =>
                            array (
                                'values' =>
                                    array (
                                        'region'    => 'Region',
                                        'dimension' => 'Dimension',
                                    ),
                                ),
                    ),
                    'position' => array(
                        'group'          => 'General',
                        'type'           => 'int',
                        'backend'        => '',
                        'frontend'       => '',
                        'label'          => 'Position',
                        'input'          => 'text',
                        'source'         => '',
                        'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
                        'required'       => '0',
                        'user_defined'   => true,
                        'default'        => '',
                        'unique'         => false,
                        'position'       => '40',
                        'note'           => '',
                        'visible'        => '1',
                        'wysiwyg_enabled'=> '0',
                    ),
                    'status' => array(
                        'group'          => 'General',
                        'type'           => 'int',
                        'backend'        => '',
                        'frontend'       => '',
                        'label'          => 'Enabled',
                        'input'          => 'select',
                        'source'         => 'eav/entity_attribute_source_boolean',
                        'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required'       => '1',
                        'user_defined'   => false,
                        'default'        => '1',
                        'unique'         => false,
                        'position'       => '50',
                        'note'           => '',
                        'visible'        => '1',
                        'wysiwyg_enabled'=> '0',
                    ),

                )
         );
        $entities['ave_sizechart_type'] = array(
            'entity_model'                  => 'ave_sizechart/type',
            'attribute_model'               => 'ave_sizechart/resource_eav_attribute',
            'table'                         => 'ave_sizechart/type',
            'additional_attribute_table'    => 'ave_sizechart/eav_attribute',
            'entity_attribute_collection'   => 'ave_sizechart/type_attribute_collection',
            'attributes'                    => array(
                    'name' => array(
                        'group'          => 'General',
                        'type'           => 'varchar',
                        'backend'        => '',
                        'frontend'       => '',
                        'label'          => 'Name',
                        'input'          => 'text',
                        'source'         => '',
                        'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required'       => '1',
                        'user_defined'   => false,
                        'default'        => '',
                        'unique'         => false,
                        'position'       => '10',
                        'note'           => 'Tops, Bottoms, Dresses, Swim, Suiting, Outerwear, Shoes, Accessories',
                        'visible'        => '1',
                        'wysiwyg_enabled'=> '0',
                    ),
                    'position' => array(
                        'group'          => 'General',
                        'type'           => 'int',
                        'backend'        => '',
                        'frontend'       => '',
                        'label'          => 'Position',
                        'input'          => 'text',
                        'source'         => '',
                        'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_GLOBAL,
                        'required'       => '0',
                        'user_defined'   => true,
                        'default'        => '',
                        'unique'         => false,
                        'position'       => '20',
                        'note'           => '',
                        'visible'        => '1',
                        'wysiwyg_enabled'=> '0',
                    ),
                    'status' => array(
                        'group'          => 'General',
                        'type'           => 'int',
                        'backend'        => '',
                        'frontend'       => '',
                        'label'          => 'Enabled',
                        'input'          => 'select',
                        'source'         => 'eav/entity_attribute_source_boolean',
                        'global'         => Mage_Catalog_Model_Resource_Eav_Attribute::SCOPE_STORE,
                        'required'       => '1',
                        'user_defined'   => false,
                        'default'        => '1',
                        'unique'         => false,
                        'position'       => '30',
                        'note'           => '',
                        'visible'        => '1',
                        'wysiwyg_enabled'=> '0',
                    ),

                )
         );
        return $entities;
    }
}
