<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
$_productCollection=$this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else : ?>
<?php if ($this->getMode()!= 'grid') : ?>
<?php
$themeHelper = $this->helper('flexibletheme');
$quickShopHelper = $this->helper('quickviewpro');
$imageHelper = $this->helper('catalog/image');
$labelHelper = $themeHelper->getLabelHelper();
$wishlistHelper = $this->helper('wishlist');
$width = $themeHelper->getConfig('images/category/product_image_width')?:300;
$height = $themeHelper->getConfig('images/category/product_image_height')?:300;
$paddingBottom = $height*100/$width;
$showDescription = $themeHelper->isDisplayOnList('description');
$showSku = $themeHelper->isDisplayOnList('sku');
$showWishlist = $wishlistHelper->isAllow() && $themeHelper->isDisplayOnList('wishlist');
$showCompare = $themeHelper->isDisplayOnList('compare');
$showCart = $themeHelper->isDisplayOnList('addtocart');
$showQuickShop = $themeHelper->isDisplayOnList('quickshop');
$showLabel = $themeHelper->isDisplayOnList('label');
$showThumb = $themeHelper->isDisplayOnList('thumb');
$showName = $themeHelper->isDisplayOnList('name');
$showReview = $themeHelper->isDisplayOnList('review');
$showPrice = $themeHelper->isDisplayOnList('price');
$layout = $themeHelper->getBlockPageLayout($this);
?>
<style type="text/css">
<?= $themeHelper->getColumnStyle('.cdz-products-grid', '.cdz-products-grid .item.product-item', '.product-items .item.product-item', $layout); ?>
</style>
<div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <?php
        $url = $_product->getProductUrl();
        $name = $this->stripTags($_product->getName(), null, true);
        ?>
        <li class="product-item item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <div class="product-item-info">
                <?php // Product Image ?>
                <div class="product-left">
                    <a href="<?= $url ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="abs-img product-image" style="padding-bottom: <?php echo $paddingBottom ?>%">
                        <img class="product-image-photo main-img" src="<?= $imageHelper->init($_product, 'small_image')->keepFrame(false)->resize($width); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        <img class="product-image-photo hovered-img" src="<?= $imageHelper->init($_product, 'thumbnail')->keepFrame(false)->resize($width); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>" id="product-collection-image-<?php echo $_product->getId(); ?>" />
                    </a>
                    <?= $showLabel?$labelHelper->showLabel($_product):''; ?>
                    <?= $showQuickShop?$quickShopHelper->getQuickShopButton($_product):''; ?>
                </div>
                <?php // Product description ?>
                <div class="product-shop">
                    <div class="f-fix">
                        <div class="product-primary">
                            <?php if ($showName): ?>
                            <strong class="product-name"><a href="<?php echo $url ?>" title="<?php echo $name; ?>"><?php echo $name; ?></a></strong>
                            <?php endif ?>
                            <?php if ($showSku) : ?>
                            <div class="product-item-sku"><span class="label"><?= __('SKU: ') ?></span><span class="value"><?= $_product->getData('sku') ?></span></div>
                            <?php endif ?>
                            <?= ($showReview && $_product->getRatingSummary()) ? $this->getReviewsSummaryHtml($_product) : ''; ?>
                            <?php
                            if ($this->getChild('name.after')) {
                                $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                                foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                    $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                    $_nameAfterChild->setProduct($_product);
                                    echo $_nameAfterChild->toHtml();
                                }
                            }
                            ?>
                        </div>
                        <?php if ($showPrice) : ?>
                        <div class="product-secondary">
                            <?= $this->getPriceHtml($_product, true); ?>
                        </div>
                        <?php endif ?>
                        <div class="product-secondary">
                            <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                                <p class="action"><button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                            <?php elseif($_product->canConfigure() && $_product->isSaleable()): ?>
                                <p class="action"><button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="CodazonAjaxCartPro.getConfigurableOptions('<?php echo $this->getUrl('quickviewpro/cart/view', array('id' => $_product->getId())) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                            <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                                <p class="action"><a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button btn-cart" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a></p>
                            <?php else: ?>
                                <p class="action availability out-of-stock"><a title="<?php echo $this->quoteEscape($this->__('Out of stock')) ?>" class="button btn-cart disabled" href="<?php echo $_product->getProductUrl() ?>"><span><?php echo $this->__('Out of stock') ?></a></p>
                            <?php endif; ?>
                            <?php if ($showWishlist || $showCompare): ?>
                            <ul class="add-to-links">
                                <?php if ($showWishlist) : ?>
                                    <li><a href="<?php echo $wishlistHelper->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                <?php endif; ?>
                                <?php if($showCompare && ($_compareUrl = $this->getAddToCompareUrl($_product))): ?>
                                    <li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>
                            </ul>
                            <?php endif; ?>
                        </div>
                        <div class="desc std">
                            <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $name ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                        </div>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>
<?php endif ?>
<?php endif ?>