<?php
/**
 * Copyright © 2017 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$helper = $this->helper('flexibletheme');
$enableCategorySearch = $helper->getConfig('flexibletheme/search_by_category/enable');
$parentId = $helper->getConfig('flexibletheme/search_by_category/category_parent_id') ? : Mage::app()->getStore()->getRootCategoryId();
$maxDepth = $helper->getConfig('flexibletheme/search_by_category/category_max_depth') ? : 0;
$allCatText = __('All Categories');
$dataSearch = array(
    'allCatText' => $allCatText,
    'currentCat' => $this->getRequest()->getParam('cat')?:false
);
?>
<?php if ($enableCategorySearch) : ?>
<div style="display:none" id="search-by-category-tmpl">
	<div class="cdz-cat-search" data-role="container" data-search='<?= json_encode($dataSearch) ?>'>
		<div class="inner">
			<a href="javascript:;" class="current-cat" data-role="trigger"><span><?= $allCatText; ?></span></a>
			<div class="category-chooser dropdown" data-role="dropdown">
				<div class="dropdown-inner">
					<ul class="category-list" data-role="category-list">
						<li><a class="all-cat"><?php echo $allCatText; ?></a></li>
						<?php echo $this->getChild('category.search.list')
                            ->setParentId($parentId)
                            ->setData('max_depth', $maxDepth)
                            ->toHtml() ?>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<?php endif ?>