<?php
/**
 * Copyright © 2018 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$helper = Mage::helper('flexibletheme');
$blockIdentifier = $helper->getConfig('flexibletheme/general/newsletter_popup');
$delay = (float)$helper->getConfig('flexibletheme/general/newsletter_popup_delay_time') ? : 0;
$frequency = (float)$helper->getConfig('flexibletheme/general/newsletter_popup_frequency') ? : 60;
$widget = array(
    'codazon.newsletterPopup' => array(
        'cookieName'        =>  'cdz-newsletter-modal',
        'frequency'         =>  $frequency,
        'delay'             =>  $delay,
        'blockIdentifier'   =>  $blockIdentifier,
        'ajaxUrl'           =>  $this->getUrl('flexibletheme/ajax/cmsblock')
    )
);
?>
<?php if ($blockIdentifier) : ?>
<div style="display:none">
<div class="cdz-newsletter-content" id="cdz-newsletter-modal" data-cdzpopup data-cdzwidget='<?= json_encode($widget) ?>'></div>
</div>
<?php endif ?>